### PR TITLE
Fix bug where EditPersonCommand unfilter displayed order list

### LINKED ISSUE #116: Fix bug where EditPersonCommand unfilter displayed order list
for eg. listOrder 1
filter completed
edit 1 n/Alex Yeo
Order list will get unfiltered

### PR DESCRIPTION
**Pull request by kaixuan477**
Close #116

### CODE REVIEW

File: src/main/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommand.java [hunk 1]
```diff
@@ -70,7 +70,6 @@ public CommandResult execute(Model model) throws CommandException {
         OrderList orderList = personToAddUnder.getOrderList();
         String feedbackToUser = orderList.contains(toAdd) ? MESSAGE_DUPLICATE_ORDER_WARNING : "";
         orderList.add(toAdd);
-        personToAddUnder.resetFilteredOrderList();
```
Comment (FooChao) [inline src/main/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommand.java:73]: u need to undo this since this is from previous version.

Comment (kaixuan477) [reply src/main/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommand.java]: Updated.
