### PR TITLE
Fix tag/customer/item duplicate handling

### LINKED ISSUE #87: Change command usage which utilise person index to be called PERSON_INDEX

### LINKED ISSUE #179: Fix bugs related to duplicate detection
image
maybe put in user guide?

### LINKED ISSUE #185: Fix tag/customer/item duplicate handling
for case sensitive

### PR DESCRIPTION
**Pull request by FooChao**
close #87 
close #179 
close #185

### CODE REVIEW

File: src/main/java/seedu/sellsavvy/logic/commands/personcommands/AddPersonCommand.java [hunk 1]
```diff
@@ -40,6 +40,12 @@ public class AddPersonCommand extends Command {
 
     public static final String MESSAGE_SUCCESS = "New person added: %1$s";
     public static final String MESSAGE_DUPLICATE_PERSON = "This person already exists in the address book.";
+    public static final String MESSAGE_SIMILAR_TAGS_WARNING = "Note: "
```
Comment (awdse22) [inline src/main/java/seedu/sellsavvy/logic/commands/personcommands/AddPersonCommand.java:43]: Since this is being used at EditPersonCommand, can this be moved to Messages.java instead?

File: src/main/java/seedu/sellsavvy/logic/commands/personcommands/AddPersonCommand.java [hunk 2]
```diff
@@ -40,6 +40,12 @@ public class AddPersonCommand extends Command {
...
+            + "This customer has 2 or more similar tags, "
+            + "verify if this is a mistake.\n";
+    public static final String MESSAGE_SIMILAR_NAME_WARNING = "Note: "
```
Comment (awdse22) [inline src/main/java/seedu/sellsavvy/logic/commands/personcommands/AddPersonCommand.java:46]: Same applies for this.

File: src/main/java/seedu/sellsavvy/logic/commands/personcommands/EditPersonCommand.java [hunk 3]
```diff
@@ -94,7 +100,15 @@ public CommandResult execute(Model model) throws CommandException {
             model.updateSelectedPerson(editedPerson);
         }
 
-        return new CommandResult(String.format(MESSAGE_EDIT_PERSON_SUCCESS, Messages.format(editedPerson)));
+        String feedbackToUser = model.hasSimilarPerson(editedPerson)
```
Comment (awdse22) [inline src/main/java/seedu/sellsavvy/logic/commands/personcommands/EditPersonCommand.java:103]: Should this also include `editPersonDescriptor.isNameEdited()`?
The check for similar tags included that condition.

File: src/main/java/seedu/sellsavvy/model/order/Item.java [hunk 4]
```diff
@@ -38,6 +39,14 @@ public static boolean isValidItem(String test) {
         return test.matches(VALIDATION_REGEX);
     }
 
+    /**
+     * Returns true if the item's full description is similar to given item's full description.
```
Comment (awdse22) [inline src/main/java/seedu/sellsavvy/model/order/Item.java:43]:
```suggestion
     * Returns true if this item's full description is similar to {@code otherItem}'s full description.
```

File: src/main/java/seedu/sellsavvy/model/person/Name.java [hunk 5]
```diff
@@ -46,6 +47,13 @@ public static boolean isValidName(String test) {
         return test.matches(VALIDATION_REGEX);
     }
 
+    /**
+     * Returns true if the name is similar to other given name.
```
Comment (awdse22) [inline src/main/java/seedu/sellsavvy/model/person/Name.java:51]:
```suggestion
     * Returns true if the name is similar to {@code otherName}.
```

File: src/test/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommandTest.java [hunk 6]
```diff
@@ -76,9 +78,31 @@ public void execute_duplicatePendingOrder_warningGiven() {
...
+    public void execute_similarPendingOrder_warningGiven() {
+        // add something similar(but not identical) to the first order to the person's order list
+        String editedItemString = normalise(ABACUS.getItem().fullDescription);
+        Order toAdd = new OrderBuilder(ABACUS).withItem(editedItemString).build();
+        AddOrderCommand addOrderCommand = new AddOrderCommand(INDEX_FIRST, toAdd);
+
+        //ensures it is not equal to ABACUS
+        assertNotEquals(toAdd, ABACUS);
+
+        model.getFilteredPersonList().get(0).getOrderList().add(toAdd.createCopy());
```
Comment (awdse22) [inline src/test/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommandTest.java:91]: Shouldn't this be adding `ABACUS` instead? From what i'm seeing, it seems you're adding a copy of `toAdd` first and then executing the addOrderCommand to add another `toAdd`, which is the same as `execute_duplicatePendingOrder_warningGiven()`

File: src/test/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommandTest.java [hunk 7]
```diff
@@ -76,9 +78,31 @@ public void execute_duplicatePendingOrder_warningGiven() {
...
+        personToAddUnder.getOrderList().add(toAdd);
+        expectedModel.updateSelectedPerson(personToAddUnder);
+        String expectedMessage = String.format(MESSAGE_DUPLICATE_ORDER_WARNING
+                + AddOrderCommand.MESSAGE_ADD_ORDER_SUCCESS, personToAddUnder.getName(), Messages.format(toAdd));
+
+        assertCommandSuccess(addOrderCommand, model, expectedMessage, expectedModel);
+    }
+
     @Test
     public void execute_duplicateCompletedOrder_success() {
```
Comment (awdse22) [inline src/test/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommandTest.java:104]: Actually is there a point in testing this? We can't add a completed order into order list as far as i know.

File: src/test/java/seedu/sellsavvy/model/AddressBookTest.java [hunk 8]
```diff
@@ -82,6 +82,37 @@ public void hasPerson_personWithSameIdentityFieldsInAddressBook_returnsTrue() {
         assertTrue(addressBook.hasPerson(editedAlice));
     }
 
+    @Test
+    public void hasSimilarPerson_noSimilar_returnsFalse() {
+        assertFalse(addressBook.hasPerson(ALICE));
```
Comment (awdse22) [inline src/test/java/seedu/sellsavvy/model/AddressBookTest.java:87]: Shouldn't this be `addressBook.hasSimilarPerson`?

**Review by awdse22 — COMMENTED** [review]
LGTM, just a few nits.

File: src/main/java/seedu/sellsavvy/logic/commands/personcommands/EditPersonCommand.java [hunk 9]
```diff
@@ -55,6 +55,12 @@ public class EditPersonCommand extends Command {
     public static final String MESSAGE_EDIT_PERSON_SUCCESS = "Edited Person: %1$s";
     public static final String MESSAGE_NOT_EDITED = "At least one field to edit must be provided.";
     public static final String MESSAGE_DUPLICATE_PERSON = "This person already exists in the address book.";
+    public static final String MESSAGE_SIMILAR_TAGS_WARNING = "Note: "
+            + "This customer has 2 or more similar tags after editing tags, "
+            + "verify if this is a mistake.\n";
+    public static final String MESSAGE_SIMILAR_NAME_WARNING = "Note: "
+            + "A person with similar name already exists in the address book, "
+            + "verify if this is a mistake.\n";
```
Comment (kaixuan477) [inline src/main/java/seedu/sellsavvy/logic/commands/personcommands/EditPersonCommand.java:63]: Messages presently do not use breakline, check if this is valid without `\n`?

Comment (kaixuan477) [reply src/main/java/seedu/sellsavvy/logic/commands/personcommands/EditPersonCommand.java:63]: Negligible effect anyway.

File: src/main/java/seedu/sellsavvy/model/order/Date.java [hunk 10]
```diff
@@ -49,10 +49,7 @@ public Date(String date) {
      * Returns if a given string is of a valid date regex.
      */
     public static boolean isValidDateRegex(String test) {
-        if (!test.matches(REGEX_DATE)) {
-            return false;
-        }
-        return true;
+        return test.matches(REGEX_DATE);
```
Comment (kaixuan477) [inline src/main/java/seedu/sellsavvy/model/order/Date.java:52]: Nice catch.

**Review by kaixuan477 — COMMENTED** [review]
Looks good, minor notes to comments. Let others check first.

File: src/main/java/seedu/sellsavvy/logic/commands/personcommands/EditPersonCommand.java (hunk 9 above)
Comment (FooChao) [reply src/main/java/seedu/sellsavvy/logic/commands/personcommands/EditPersonCommand.java:63]: it need to break line so because there can be multiple warnings and we need ensure it is at different line if there is a warning already

File: src/main/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommand.java [hunk 11]
```diff
@@ -41,7 +41,7 @@ public class AddOrderCommand extends Command {
 
     public static final String MESSAGE_ADD_ORDER_SUCCESS = "New order added for %1$s: %2$s";
     public static final String MESSAGE_DUPLICATE_ORDER_WARNING = "Note: "
-            + "This customer already has a pending order with the same details, "
+            + "This customer already has a pending order with the similar details, "
```
[the remark this answers is not in the document]
Comment (FooChao) [reply src/main/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommand.java]: in

File: src/main/java/seedu/sellsavvy/logic/commands/ordercommands/EditOrderCommand.java [hunk 12]
```diff
@@ -48,7 +48,7 @@ public class EditOrderCommand extends Command {
     public static final String MESSAGE_EDIT_ORDER_SUCCESS = "Edited Order: %1$s";
     public static final String MESSAGE_NOT_EDITED = "At least one field to edit must be provided.";
     public static final String MESSAGE_DUPLICATE_ORDER_WARNING = "Note: "
-            + "This customer already has a %1$s order with the same details, "
+            + "This customer already has a %1$s order with the similar details, "
```
[the remark this answers is not in the document]
Comment (FooChao) [reply src/main/java/seedu/sellsavvy/logic/commands/ordercommands/EditOrderCommand.java]: in

File: src/main/java/seedu/sellsavvy/logic/commands/personcommands/AddPersonCommand.java (hunk 1 above)
Comment (FooChao) [reply src/main/java/seedu/sellsavvy/logic/commands/personcommands/AddPersonCommand.java:44]: similar tags warning is different.

File: src/main/java/seedu/sellsavvy/logic/commands/personcommands/AddPersonCommand.java (hunk 2 above)
Comment (FooChao) [reply src/main/java/seedu/sellsavvy/logic/commands/personcommands/AddPersonCommand.java]: in

File: src/main/java/seedu/sellsavvy/logic/commands/personcommands/EditPersonCommand.java (hunk 3 above)
Comment (FooChao) [reply src/main/java/seedu/sellsavvy/logic/commands/personcommands/EditPersonCommand.java]: in

File: src/main/java/seedu/sellsavvy/model/order/Order.java [hunk 13]
```diff
@@ -67,6 +67,18 @@ public boolean hasDateElapsed() {
         return date.hasDateElapsed();
     }
 
+    /**
+     * Returns true if the order is similar to given order.
+     * Two order names are considered similar if they have similar/identical name
+     * and identical quantity, date and status as the given argument.
```
[the remark this answers is not in the document]
Comment (FooChao) [reply src/main/java/seedu/sellsavvy/model/order/Order.java]: in

File: src/main/java/seedu/sellsavvy/model/order/OrderList.java [hunk 14]
```diff
@@ -36,6 +36,15 @@ public boolean containsDuplicateOrder(Order toCheck) {
         return internalList.stream().anyMatch(order -> toCheck.equals(order) && toCheck != order);
     }
 
+    /**
+     * Returns true if the list contains a different order with similar/identical name
+     * and identical quantity, date and status as the given argument.
```
[the remark this answers is not in the document]
Comment (FooChao) [reply src/main/java/seedu/sellsavvy/model/order/OrderList.java]: in

File: src/test/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommandTest.java (hunk 6 above)
Comment (FooChao) [reply src/test/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommandTest.java]: in

File: src/test/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommandTest.java (hunk 7 above)
Comment (FooChao) [reply src/test/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommandTest.java:108]: the purpose of this is to ensure that there is a duplcate with diff status no warning is thrown. I will add comment to help clarify and this code is by u in the first place...

File: src/test/java/seedu/sellsavvy/model/AddressBookTest.java (hunk 8 above)
Comment (FooChao) [reply src/test/java/seedu/sellsavvy/model/AddressBookTest.java]: in

File: src/test/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommandTest.java (hunk 7 above)
Comment (awdse22) [reply src/test/java/seedu/sellsavvy/logic/commands/ordercommands/AddOrderCommandTest.java:108]: that works then

**Review by awdse22 — APPROVED** [review]
